---
# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

MD013: false

MD024:
  siblings_only: true

MD029: false

MD033: false

MD041: false

MD040: false

MD060: false
