/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — returns healthy if the service is running.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — returns ready if the database is reachable.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Locations
         * @description List OwnTracks locations with filtering and pagination.
         */
        get: operations["list_locations_api_v1_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description List all distinct device IDs.
         */
        get: operations["list_devices_api_v1_locations_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Count
         * @description Get total location count with optional filters.
         */
        get: operations["location_count_api_v1_locations_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Location
         * @description Get a single location by ID, including raw payload.
         */
        get: operations["get_location_api_v1_locations__location_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/garmin/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activities
         * @description List Garmin activities with filtering and pagination.
         */
        get: operations["list_activities_api_v1_garmin_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/garmin/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sports
         * @description List distinct sport types with activity counts.
         */
        get: operations["list_sports_api_v1_garmin_sports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/garmin/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description Get a single Garmin activity by ID with track point count.
         */
        get: operations["get_activity_api_v1_garmin_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/garmin/activities/{activity_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Track Points
         * @description List track points for a specific activity.
         */
        get: operations["list_track_points_api_v1_garmin_activities__activity_id__tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gps/unified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Unified Gps
         * @description Query the unified_gps_points view combining OwnTracks + Garmin data.
         */
        get: operations["list_unified_gps_api_v1_gps_unified_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gps/daily-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily Summary
         * @description Query the daily_activity_summary view for aggregated daily stats.
         */
        get: operations["daily_summary_api_v1_gps_daily_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference-locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reference Locations
         * @description List all reference locations.
         */
        get: operations["list_reference_locations_api_v1_reference_locations_get"];
        put?: never;
        /**
         * Create Reference Location
         * @description Create a new reference location (auth required).
         */
        post: operations["create_reference_location_api_v1_reference_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference-locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reference Location
         * @description Get a single reference location by ID.
         */
        get: operations["get_reference_location_api_v1_reference_locations__location_id__get"];
        /**
         * Update Reference Location
         * @description Update a reference location (auth required).
         */
        put: operations["update_reference_location_api_v1_reference_locations__location_id__put"];
        post?: never;
        /**
         * Delete Reference Location
         * @description Delete a reference location (auth required).
         */
        delete: operations["delete_reference_location_api_v1_reference_locations__location_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spatial/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Nearby
         * @description Find GPS points within a radius of a given lat/lon using PostGIS ST_DWithin.
         */
        get: operations["find_nearby_api_v1_spatial_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spatial/distance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate Distance
         * @description Calculate the distance in meters between two points using PostGIS ST_Distance.
         */
        get: operations["calculate_distance_api_v1_spatial_distance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spatial/within-reference/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Within Reference
         * @description Find all GPS points within a named reference location's radius.
         */
        get: operations["within_reference_api_v1_spatial_within_reference__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** DailyActivitySummary */
        DailyActivitySummary: {
            /** Activity Date */
            activity_date?: string | null;
            /** Owntracks Device */
            owntracks_device?: string | null;
            /** Owntracks Points */
            owntracks_points?: number | null;
            /** Min Battery */
            min_battery?: number | null;
            /** Max Battery */
            max_battery?: number | null;
            /** Avg Accuracy */
            avg_accuracy?: number | null;
            /** Garmin Sport */
            garmin_sport?: string | null;
            /** Garmin Activities */
            garmin_activities?: number | null;
            /** Total Distance Km */
            total_distance_km?: number | null;
            /** Total Duration Seconds */
            total_duration_seconds?: number | null;
            /** Avg Heart Rate */
            avg_heart_rate?: number | null;
            /** Total Calories */
            total_calories?: number | null;
        };
        /** DeviceInfo */
        DeviceInfo: {
            /** Device Id */
            device_id: string;
        };
        /** DistanceResult */
        DistanceResult: {
            /** Distance Meters */
            distance_meters: number;
            /** From Lat */
            from_lat: number;
            /** From Lon */
            from_lon: number;
            /** To Lat */
            to_lat: number;
            /** To Lon */
            to_lon: number;
        };
        /** GarminActivity */
        GarminActivity: {
            /** Activity Id */
            activity_id: string;
            /** Sport */
            sport: string;
            /** Sub Sport */
            sub_sport?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Avg Heart Rate */
            avg_heart_rate?: number | null;
            /** Max Heart Rate */
            max_heart_rate?: number | null;
            /** Avg Cadence */
            avg_cadence?: number | null;
            /** Max Cadence */
            max_cadence?: number | null;
            /** Calories */
            calories?: number | null;
            /** Avg Speed Kmh */
            avg_speed_kmh?: number | null;
            /** Max Speed Kmh */
            max_speed_kmh?: number | null;
            /** Total Ascent M */
            total_ascent_m?: number | null;
            /** Total Descent M */
            total_descent_m?: number | null;
            /** Total Distance */
            total_distance?: number | null;
            /** Avg Pace */
            avg_pace?: number | null;
            /** Device Manufacturer */
            device_manufacturer?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Uploaded At */
            uploaded_at?: string | null;
            /** Track Point Count */
            track_point_count?: number | null;
        };
        /** GarminTrackPoint */
        GarminTrackPoint: {
            /** Id */
            id: number;
            /** Activity Id */
            activity_id: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Altitude */
            altitude?: number | null;
            /** Distance From Start Km */
            distance_from_start_km?: number | null;
            /** Speed Kmh */
            speed_kmh?: number | null;
            /** Heart Rate */
            heart_rate?: number | null;
            /** Cadence */
            cadence?: number | null;
            /** Temperature C */
            temperature_c?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Location */
        Location: {
            /** Id */
            id: number;
            /** Device Id */
            device_id: string;
            /** Tid */
            tid?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Accuracy */
            accuracy?: number | null;
            /** Altitude */
            altitude?: number | null;
            /** Velocity */
            velocity?: number | null;
            /** Battery */
            battery?: number | null;
            /** Battery Status */
            battery_status?: number | null;
            /** Connection Type */
            connection_type?: string | null;
            /** Trigger */
            trigger?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Created At */
            created_at?: string | null;
        };
        /** LocationCount */
        LocationCount: {
            /** Count */
            count: number;
            /** Date */
            date?: string | null;
            /** Device Id */
            device_id?: string | null;
        };
        /** LocationDetail */
        LocationDetail: {
            /** Id */
            id: number;
            /** Device Id */
            device_id: string;
            /** Tid */
            tid?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Accuracy */
            accuracy?: number | null;
            /** Altitude */
            altitude?: number | null;
            /** Velocity */
            velocity?: number | null;
            /** Battery */
            battery?: number | null;
            /** Battery Status */
            battery_status?: number | null;
            /** Connection Type */
            connection_type?: string | null;
            /** Trigger */
            trigger?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Created At */
            created_at?: string | null;
            /** Raw Payload */
            raw_payload?: Record<string, never> | null;
        };
        /** NearbyPoint */
        NearbyPoint: {
            /** Source */
            source: string;
            /** Id */
            id: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Distance Meters */
            distance_meters: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** PaginatedResponse[GarminActivity] */
        PaginatedResponse_GarminActivity_: {
            /** Items */
            items: components["schemas"]["GarminActivity"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PaginatedResponse[GarminTrackPoint] */
        PaginatedResponse_GarminTrackPoint_: {
            /** Items */
            items: components["schemas"]["GarminTrackPoint"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PaginatedResponse[Location] */
        PaginatedResponse_Location_: {
            /** Items */
            items: components["schemas"]["Location"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PaginatedResponse[UnifiedGpsPoint] */
        PaginatedResponse_UnifiedGpsPoint_: {
            /** Items */
            items: components["schemas"]["UnifiedGpsPoint"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ReferenceLocation */
        ReferenceLocation: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Radius Meters
             * @default 50
             */
            radius_meters: number;
            /** Description */
            description?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ReferenceLocationCreate */
        ReferenceLocationCreate: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Radius Meters
             * @default 50
             */
            radius_meters: number;
            /** Description */
            description?: string | null;
        };
        /** ReferenceLocationUpdate */
        ReferenceLocationUpdate: {
            /** Name */
            name?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Radius Meters */
            radius_meters?: number | null;
            /** Description */
            description?: string | null;
        };
        /** SportInfo */
        SportInfo: {
            /** Sport */
            sport: string;
            /** Activity Count */
            activity_count: number;
        };
        /** UnifiedGpsPoint */
        UnifiedGpsPoint: {
            /** Source */
            source: string;
            /** Identifier */
            identifier: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Accuracy */
            accuracy?: number | null;
            /** Battery */
            battery?: number | null;
            /** Speed Kmh */
            speed_kmh?: number | null;
            /** Heart Rate */
            heart_rate?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WithinReferenceResult */
        WithinReferenceResult: {
            /** Reference Name */
            reference_name: string;
            /** Radius Meters */
            radius_meters: number;
            /** Total Points */
            total_points: number;
            /** Points */
            points: components["schemas"]["NearbyPoint"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_locations_api_v1_locations_get: {
        parameters: {
            query?: {
                device_id?: string | null;
                /** @description Filter from date (YYYY-MM-DD) */
                date_from?: string | null;
                /** @description Filter to date (YYYY-MM-DD) */
                date_to?: string | null;
                limit?: number;
                offset?: number;
                /** @description Sort column */
                sort?: string;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Location_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_locations_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceInfo"][];
                };
            };
        };
    };
    location_count_api_v1_locations_count_get: {
        parameters: {
            query?: {
                /** @description Filter by date (YYYY-MM-DD) */
                date?: string | null;
                device_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationCount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_location_api_v1_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_v1_garmin_activities_get: {
        parameters: {
            query?: {
                sport?: string | null;
                /** @description Filter from date (YYYY-MM-DD) */
                date_from?: string | null;
                /** @description Filter to date (YYYY-MM-DD) */
                date_to?: string | null;
                limit?: number;
                offset?: number;
                /** @description Sort column */
                sort?: string;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_GarminActivity_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sports_api_v1_garmin_sports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportInfo"][];
                };
            };
        };
    };
    get_activity_api_v1_garmin_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarminActivity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_track_points_api_v1_garmin_activities__activity_id__tracks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Sort column */
                sort?: string;
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_GarminTrackPoint_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_unified_gps_api_v1_gps_unified_get: {
        parameters: {
            query?: {
                /** @description Filter by source: owntracks or garmin */
                source?: string | null;
                /** @description Filter from date (YYYY-MM-DD) */
                date_from?: string | null;
                /** @description Filter to date (YYYY-MM-DD) */
                date_to?: string | null;
                limit?: number;
                offset?: number;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_UnifiedGpsPoint_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_summary_api_v1_gps_daily_summary_get: {
        parameters: {
            query?: {
                /** @description Filter from date (YYYY-MM-DD) */
                date_from?: string | null;
                /** @description Filter to date (YYYY-MM-DD) */
                date_to?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyActivitySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reference_locations_api_v1_reference_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceLocation"][];
                };
            };
        };
    };
    create_reference_location_api_v1_reference_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceLocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceLocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reference_location_api_v1_reference_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceLocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_reference_location_api_v1_reference_locations__location_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceLocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceLocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reference_location_api_v1_reference_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_nearby_api_v1_spatial_nearby_get: {
        parameters: {
            query: {
                /** @description Latitude of center point */
                lat: number;
                /** @description Longitude of center point */
                lon: number;
                /** @description Search radius in meters */
                radius_meters?: number;
                /** @description Filter by source: owntracks or garmin */
                source?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_distance_api_v1_spatial_distance_get: {
        parameters: {
            query: {
                /** @description From latitude */
                from_lat: number;
                /** @description From longitude */
                from_lon: number;
                /** @description To latitude */
                to_lat: number;
                /** @description To longitude */
                to_lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistanceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    within_reference_api_v1_spatial_within_reference__name__get: {
        parameters: {
            query?: {
                /** @description Filter by source: owntracks or garmin */
                source?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithinReferenceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
